baseURL = "/"
languageCode = "en-us"
title = "Fabio S. Takaki - TakakiME"
theme = "takakime"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[markup.goldmark.renderer]
    unsafe = true