name: Build and Deploy Hugo

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: Deploy

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Include CNAME if present
        if: ${{ hashFiles('CNAME') != '' }}
        run: |
          cp CNAME public/CNAME

      - name: Deploy to fabiotakaki.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: fabiotakaki/fabiotakaki.github.io
          publish_branch: master
          publish_dir: ./public
